// GENERATED by scripts/sync_nodes.py from the live n8n workflow — do not edit here.
// Edit in n8n, then re-run the script; the workflow is the system of record.
// Node: Build request

const cfg = $('Config').first().json;
const lookbackDays = cfg.lookbackDays || 30;
const runDate = new Date().toISOString().slice(0,10);
const HASHTAGS = (cfg.hashtags || ['thatsafirst','tryingnewthings','tryingsomethingnew','newexperience','newexperiences'])
  .map(h => String(h).replace(/^#/, '').toLowerCase());

// Canonicalize a post URL for robust dedup: lowercase, strip query/fragment,
// drop protocol + www, unify Instagram reel/tv -> p, remove trailing slash.
const canon = (u) => {
  let s = String(u || '').trim().toLowerCase().split('#')[0].split('?')[0];
  s = s.replace(/^https?:\/\//, '').replace(/^www\./, '');
  s = s.replace(/\/(reel|reels|tv)\//, '/p/');
  s = s.replace(/\/+$/, '');
  return s;
};

const proxy = (u) => u ? ('https://wsrv.nl/?url=' + encodeURIComponent(u) + '&w=360&output=jpg') : '';

let ig = [];
try { ig = $('Apify - Instagram').all().map(i => i.json); } catch (e) {}
let tt = [];
try { tt = $('Apify - TikTok').all().map(i => i.json); } catch (e) {}

const norm = [];
for (const p of ig) {
  const rawImg = p.displayUrl || (Array.isArray(p.images) ? p.images[0] : '') || '';
  norm.push({
    platform: 'Instagram',
    url: p.url || (p.shortCode ? ('https://www.instagram.com/p/' + p.shortCode + '/') : ''),
    text: p.caption || '',
    likes: (p.likesCount != null ? p.likesCount : null),
    comments: (p.commentsCount != null ? p.commentsCount : null),
    date: p.timestamp || '',
    image: proxy(rawImg),
    location: p.locationName || '',
    hashtags: Array.isArray(p.hashtags) ? p.hashtags.map(h => '#' + String(h).replace(/^#/, '')).join(' ') : ''
  });
}
for (const p of tt) {
  const vmeta = p.videoMeta || {};
  const rawImg = vmeta.coverUrl || (Array.isArray(p.covers) ? p.covers[0] : '') || '';
  let tth = '';
  if (Array.isArray(p.hashtags)) tth = p.hashtags.map(h => '#' + String(h && h.name ? h.name : h).replace(/^#/, '')).join(' ');
  norm.push({
    platform: 'TikTok',
    url: p.webVideoUrl || p.postPage || '',
    text: p.text || '',
    likes: (p.diggCount != null ? p.diggCount : null),
    comments: (p.commentCount != null ? p.commentCount : null),
    date: p.createTimeISO || (p.createTime ? new Date(p.createTime * 1000).toISOString() : ''),
    image: proxy(rawImg),
    location: '',
    hashtags: tth
  });
}

const cutoff = Date.now() - lookbackDays * 24 * 3600 * 1000;
let cands = norm.filter(c => {
  if (!c.url) return false;
  const t = Date.parse(c.date);
  return isNaN(t) || t >= cutoff;
});

// NOTE: $('Get sent') throws if that node has not executed yet. It must be
// wired IN LINE before Build request, not on a parallel branch -- n8n runs a
// parallel leaf branch at the END of the run, so the reference would be empty
// and dedup would silently pass everything through. Fail loudly instead.
let sentRows;
try { sentRows = $('Get sent').all(); }
catch (e) { throw new Error('Get sent has not executed before Build request - check node wiring/order. ' + e.message); }
const sent = sentRows.map(i => canon(i.json.url));
const sentSet = new Set(sent.filter(Boolean));
cands = cands.filter(c => !sentSet.has(canon(c.url)));

// Drop duplicates within this run (same canonical URL from IG+TikTok or reposts).
const seenNow = new Set();
cands = cands.filter(c => { const k = canon(c.url); if (seenNow.has(k)) return false; seenNow.add(k); return true; });

// Prioritize likely GENUINE first-time posts for analysis (cheap text heuristic), then engagement.
const firstRe = /first[ -]?time|1st time|day one|day 1|for the first|my first|took my first|tried .{0,15}for the first|learn(ing|ed|t) to|first attempt|beginner|bucket list|elet[eé]mben|el[oő]sz[oö]r|els[oő] alkalom|kipr[oó]b[aá]l/i;
const fscore = (c) => firstRe.test(String(c.text || '')) ? 1 : 0;
cands.sort((a,b) => (fscore(b) - fscore(a)) || (((b.likes||0)+(b.comments||0)) - ((a.likes||0)+(a.comments||0))));
cands = cands.slice(0, 30);

// ── Hashtag deltas: today's total vs. the most recent earlier stored total ──
let statRows = [];
try { statRows = $('Apify - Hashtag stats').all().map(i => i.json); } catch (e) {}
const todayCounts = {};
for (const r of statRows) {
  const name = String(r.hashtag != null ? r.hashtag : (r.name != null ? r.name : (r.query != null ? r.query : (r.tag != null ? r.tag : ''))))
    .replace(/^#/, '').toLowerCase();
  const n = Number(r.postsCount != null ? r.postsCount : (r.posts != null ? r.posts : r.mediaCount));
  if (name && isFinite(n)) todayCounts[name] = n;
}

const prev = {};
let countRows;
try { countRows = $('Get counts').all().map(i => i.json); }
catch (e) { throw new Error('Get counts has not executed before Build request - check node wiring/order. ' + e.message); }
for (const r of countRows) {
  const name = String(r.hashtag || '').replace(/^#/, '').toLowerCase();
  const d = String(r.checked_date || '');
  if (!name || !d || d >= runDate) continue;
  if (!prev[name] || d > prev[name].checked_date) prev[name] = { checked_date: d, posts_count: Number(r.posts_count) || 0 };
}

const dayDiff = (a, b) => Math.max(1, Math.round((Date.parse(a) - Date.parse(b)) / 86400000));

const hashtagStats = HASHTAGS
  .filter(h => todayCounts[h] !== undefined)
  .map(h => {
    const postsCount = todayCounts[h];
    const p = prev[h];
    return {
      hashtag: h,
      postsCount: postsCount,
      checked_date: runDate,
      first: !p,
      delta: p ? Math.max(0, postsCount - p.posts_count) : null,
      spanDays: p ? dayDiff(runDate, p.checked_date) : null
    };
  });

const system = [
'Te egy napi felfedező szerkesztő vagy. A bemenetben Instagram és TikTok posztok jelöltjei vannak (szöveges adatok, [index] hivatkozással). Válassz ki legfeljebb 5 posztot, ahol valaki ELŐSZÖR csinál valamit. A döntéshez és a paraméterekhez a poszt SZÖVEGÉT (caption, hashtagek, helyszín) használd. Írj végig helyes, ÉKEZETES magyar nyelven (á, é, í, ó, ö, ő, ú, ü, ű).',
'',
'Kiválasztás: csak VALÓDI, SZEMÉLYES első alkalom — amikor valaki életében először próbál ki vagy tanul meg egy tevékenységet/készséget, legyőz egy félelmet, vagy átél egy jelentőségteljes első élményt (pl. szörfözés, boulderezés, korcsolyázás, főzés, vezetés, ejtőernyőzés).',
'NE válaszd (kizárás): reklám, promóció, márka- vagy terméknépszerűsítés; fizetős attrakció vagy szórakoztató termék puszta fogyasztása (pl. 5D/5DX/XD/4D mozi, vidámpark, mozijegy, koncert- vagy belépőjegy) — ez NEM valódi, személyes első; általános "fun"/vírusos tartalom, ami nem megtanult készség vagy átélt személyes mérföldkő; engagement-bait, kihívás-spam, mesterséges vagy AI-generált tartalom.',
'Ha kevesebb mint 5 igazán jó jelölt van, VÁLASSZ KEVESEBBET (akár 0-t) — inkább kevés, de valódi.',
'',
'Minden kiválasztott poszthoz add meg:',
'- index: a jelölt [index]-e a bemenetből (egész szám).',
'- line: a leíró szöveg (a platform NEVE NÉLKÜL és a link nélkül — azt később hozzáadjuk). Egy sor, kötőjellel " - " elválasztott szegmensekből: {tevékenység, benne a helyszín ha van} - {társas kontextus} [- ha valakitől tanulta] [- social proof, ha van: pl. "205 like, 12 komment"].',
'    KRITIKUS: a line MINDIG a TEVÉKENYSÉG NEVÉVEL kezdődjön (jellemzően főnév): pl. "Szörfözés", "Boulderezés", "Garnélakóstoló", "Önvezető autós út", "Analóg fotózás". SZIGORÚAN TILOS ezekkel kezdeni: "Először", "Első", "Elsőként", "Kipróbálta", "First". Az, hogy első alkalom, adott — ne mondd ki. Ne szerepeljen benne emberek neve.',
'    A társas kontextust MINDIG jelezd egy röviddel: "egyedül", "ketten", "társasággal", "csoportosan", vagy ha tanulta: "oktatóval"/"tanárral". Ha nem derül ki, "egyedül".',
'- csoportos (boolean): többen csinálták együtt (nem egyedül)? A szöveg alapján.',
'- oktatos (boolean): edző/tanár/host/vezető tanította/vezette?',
'- felnott (boolean): a tevékenységet végző személy felnőtt (nem tini/gyerek)? A szöveg alapján becsüld; ha bizonytalan, true.',
'',
'Ne találj ki adatot a szöveghez (hely, engagement). A válaszod KIZÁRÓLAG egyetlen json objektum legyen, pontosan ilyen szerkezettel:',
'{"picks":[{"index":0,"line":"Fazekaskorong, Budapest - oktatóval - 205 like, 12 komment","csoportos":true,"oktatos":true,"felnott":true}]}',
'Ha egyetlen jelölt sem felel meg, akkor: {"picks":[]}',
'A sorrend nem számít, azt később rendezzük.'
].join('\n');

const lines = cands.map((c,i) => '[' + i + '] platform=' + c.platform + ' | like=' + c.likes + ' komment=' + c.comments + ' | hely=' + (c.location||'-') + ' | hashtag=' + (c.hashtags||'-') + ' | szoveg="' + String(c.text||'').replace(/\s+/g,' ').slice(0,300) + '"');

const body = {
  // Groq's free tier, called DIRECTLY with our own key. The shared Meetapedia
  // gateway answered 'all providers rate limited' even with 13k daily requests
  // unspent: its crawler saturates every per-minute window (2026-08-19).
  // Measured against the real 30-candidate request: 120b keeps the Hungarian
  // line format, 20b drifts into English, qwen fails json_object outright.
  model: 'openai/gpt-oss-120b',
  // Groq counts prompt + max_tokens against ONE 8000 tokens-per-minute window,
  // and it does so BEFORE generating: a 3400-token prompt plus max_tokens 8000
  // is a flat 413, never a truncated answer. This is also the reasoning budget
  // (gpt-oss thinks by default; 2026-08-07 showed what an exhausted one costs).
  // Sized for the WORST case, not the observed one: 30 candidates x 300-char
  // captions is a ~4600-token prompt, so 4000 would have been a 413 on a day
  // with long captions (caught by tests/build-request.test.mjs, never in
  // production). 4600 + 3000 = 7600 <= 8000. Measured need: 805 tokens.
  max_tokens: 3000,
  // 'low' beat 'medium' on the real request twice over: 805 completion tokens
  // instead of 1296, and cleaner picks -- 'medium' returned the same activity
  // twice and one self-contradicting line.
  reasoning_effort: 'low',
  stream: false,
  response_format: { type: 'json_object' },
  messages: [
    { role: 'system', content: system },
    { role: 'user', content: 'Mai dátum: ' + runDate + '\nJelöltek (a [index] hivatkozik rájuk):\n' + lines.join('\n') + '\n\nAdd vissza a json választ.' }
  ]
};

// Diagnostics: a silently-empty dedup read is what made this class of bug
// invisible for weeks. Surface the input sizes in the node output.
return [ { json: { body: body, runDate: runDate, candidateCount: cands.length, cands: cands,
                   hashtagStats: hashtagStats, sentRowCount: sentRows.length, countsRowCount: countRows.length } } ];
