// GENERATED by scripts/sync_nodes.py from the live n8n workflow — do not edit here.
// Edit in n8n, then re-run the script; the workflow is the system of record.
// Node: Split picks

const p = $('Parse response').first().json;
const picks = p.picks || [];
const runDate = p.runDate;
return picks.map(x => ({ json: {
  url: (x.url || '').split('?')[0],
  platform: x.platform || '',
  creator: '',
  activity: x.line || '',
  sent_date: runDate
} }));
