// GENERATED by scripts/sync_nodes.py from the live n8n workflow — do not edit here.
// Edit in n8n, then re-run the script; the workflow is the system of record.
// Node: Split counts

// n8n Code node: "Split counts"  —  Run Once for All Items
// Hangs off "Build request", NOT off the Gmail path: today's totals must be
// stored even on days when no email is sent, or tomorrow's delta breaks.

const src = $('Build request').first().json;
const runDate = src.runDate;

return (src.hashtagStats || []).map((h) => ({
  json: {
    hashtag: h.hashtag,
    posts_count: h.postsCount,
    checked_date: runDate,
  },
}));
