#!/usr/bin/env python3
"""Mirror the live n8n Code nodes into nodes/*.js so they are version-controlled.

The workflow is the system of record — this pulls FROM it, never pushes to it.
Without this, the only copy of the pipeline's logic lives inside a web UI: no
diff, no review, no test. See format/engineering-practices.md.

Usage:  python3 scripts/sync_nodes.py [--check]
        --check exits 1 if the repo copy differs from the live workflow.
"""
import json, os, re, sys, urllib.request

CFG = os.path.expanduser("~/.n8n-claude.json")
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = ("// GENERATED by scripts/sync_nodes.py from the live n8n workflow — do not edit here.\n"
          "// Edit in n8n, then re-run the script; the workflow is the system of record.\n"
          "// Node: {name}\n")


def fetch_nodes():
    cfg = json.load(open(CFG))
    req = urllib.request.Request(cfg["host"] + "/api/v1/workflows/" + cfg["workflowId"],
                                 headers={"X-N8N-API-KEY": cfg["apiKey"]})
    wf = json.load(urllib.request.urlopen(req))
    return {n["name"]: n["parameters"]["jsCode"]
            for n in wf["nodes"] if n["type"] == "n8n-nodes-base.code"}


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def main():
    check = "--check" in sys.argv
    drift = []
    live = fetch_nodes()
    # A node deleted in n8n must not linger here: a stale file would keep being
    # tested and read as if it still ran. Found the hard way when the hashtag
    # nodes were removed and split-counts.js stayed behind.
    keep = {slug(n) + ".js" for n in live}
    for f in sorted(os.listdir(os.path.join(HERE, "nodes"))):
        if f.endswith(".js") and f not in keep:
            if check:
                drift.append(f + " (deleted in n8n)")
                print(f"  DRIFT      nodes/{f} — node no longer exists")
            else:
                os.remove(os.path.join(HERE, "nodes", f))
                print(f"  removed    nodes/{f} — node no longer exists")
    for name, code in sorted(live.items()):
        path = os.path.join(HERE, "nodes", slug(name) + ".js")
        want = HEADER.format(name=name) + "\n" + code.rstrip() + "\n"
        have = open(path).read() if os.path.exists(path) else None
        if want == have:
            print(f"  unchanged  {os.path.relpath(path, HERE)}")
            continue
        if check:
            drift.append(name)
            print(f"  DRIFT      {os.path.relpath(path, HERE)}")
        else:
            open(path, "w").write(want)
            print(f"  {'updated' if have else 'created'}    {os.path.relpath(path, HERE)}")
    if check and drift:
        print(f"\n{len(drift)} node(s) differ from the live workflow: {', '.join(drift)}")
        print("Run scripts/sync_nodes.py (no flag) and commit the result.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
